openapi: 3.1.0
info:
  version: 1.0-oas3.1
  title: Spring Framework Guru OpenAPI Course
  description: For Udemy course about OpenAPI by John Thompson
  contact:
    name: John Thompson
    url: https://springframework.guru
    email: jt@aol.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms
servers:
- url: https://dev.example.com
  description: Development Server
- url: https://qa.example.com
  description: QA Server
- url: https://prod.example.com
  description: Production Server
paths:
  /v1/customers:
    get:
      description: Returns all customers.
      responses:
        "200":
          description: List of Customers.
  /v1/beers:
    get:
      description: "Returns all beers if they exist; otherwise, return not found."
      responses:
        "200":
          description: List of Beers.
        "404":
          description: Oh no! We're all out of beer! ☹
  /v1/nachos:
    get:
      description: Get some nachos.
      deprecated: true
      responses:
        "404":
          description: We don't serve nachos anymore.
components: {}
